import "./types/SidechatTypes.js";
import SidechatAPIError from "./classes/SidechatAPIError.js";
const defaultHeaders = {
  Accept: "application/json",
  "Content-Type": "application/json",
};

/**
 * Initiate the login process with a phone number.  Should be followed up with verifySMSCode().
 * @param {Number} phoneNumber - US phone number (WITHOUT +1) to send verification code to
 */
const loginViaSMS = async (phoneNumber) => {
  try {
    const res = await fetch(`https://api.sidechat.lol/v1/login_register`, {
      method: "POST",
      headers: defaultHeaders,
      body: JSON.stringify({
        phone_number: `+1${phoneNumber}`,
        version: 3,
      }),
    });
    const json = await res.json();
    return json;
  } catch (err) {
    console.error(error);
    throw new SidechatAPIError("Failed to request SMS verification.");
  }
};

/**
 * Verify the code sent via SMS with loginViaSMS().
 * @param {Number} phoneNumber - US phone number (WITHOUT +1) that verification code was sent to
 * @param {String} code  - the verification code
 */
const verifySMSCode = async (phoneNumber, code) => {
  try {
    const res = await fetch(`https://api.sidechat.lol/v1/verify_phone_number`, {
      method: "POST",
      headers: defaultHeaders,
      body: JSON.stringify({
        phone_number: `+1${phoneNumber}`,
        code: code.toUpperCase(),
      }),
    });
    const json = await res.json();
    return json;
  } catch (err) {
    console.error(err);
    throw new SidechatAPIError("Failed verify this code.");
  }
};

/**
 * Set the user's age
 * @param {Number} age - user's age in years
 * @param {String} registrationID  - the registration ID generated by verifySMSCode()
 */
const setAge = async (age, registrationID) => {
  if (age < 13) {
    throw new SidechatAPIError("You're too young to use Offsides.");
  }
  try {
    const res = await fetch(
      `https://api.sidechat.lol/v1/complete_registration`,
      {
        method: "POST",
        headers: defaultHeaders,
        body: JSON.stringify({
          age: Number(age),
          registration_id: registrationID,
        }),
      }
    );
    const json = await res.json();
    return json;
  } catch (err) {
    console.error(err);
    throw new SidechatAPIError("Failed verify this code.");
  }
};

/**
 * Initiate the email setup process.  Should be followed up with checkEmailVerification().
 * @param {String} email - school email address to send verification code to
 * @param {String} token - user bearer token
 */
const registerEmail = async (email, token) => {
  try {
    const res = await fetch(
      `https://api.sidechat.lol/v2/users/register_email`,
      {
        method: "POST",
        headers: {
          ...defaultHeaders,
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          email: email,
        }),
      }
    );
    const json = await res.json();
    if (json.message) {
      throw new SidechatAPIError(json.message);
    }
    return json;
  } catch (err) {
    console.error(error);
    throw new SidechatAPIError("Failed to request email verification.");
  }
};

/**
 * Check is the user's email is verified.
 * @param {String} token - user bearer token
 */
const checkEmailVerification = async (token) => {
  try {
    const res = await fetch(
      `https://api.sidechat.lol/v1/users/check_email_verified`,
      {
        method: "GET",
        headers: {
          ...defaultHeaders,
          Authorization: `Bearer ${token}`,
        },
      }
    );
    const json = await res.json();
    if (json.verified_email_updates_response) {
      return json.verified_email_updates_response;
    } else {
      throw new SidechatAPIError(json?.message || "Email is not verified.");
    }
  } catch (err) {
    console.error(error);
    throw new SidechatAPIError("Email is not verified.");
  }
};

/**
 * Set the device ID of the current user
 * @param {String} deviceId - the device ID to set
 * @param {String} token  - the user bearer token
 */
const setDeviceID = async (deviceID, token) => {
  try {
    const res = await fetch(
      `https://api.sidechat.lol/v1/register_device_token`,
      {
        method: "POST",
        headers: {
          ...defaultHeaders,
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          build_type: "release",
          bundle_id: "com.flowerave.sidechat",
          device_token: deviceID,
        }),
      }
    );
    const json = await res.json();
    await AsyncStorage.setItem("deviceID", deviceID);
    return json;
  } catch (err) {
    console.error(err);
    throw new SidechatAPIError("Failed verify this code.");
  }
};

/**
 * Get updated status for user and group
 * @param {String} token - user bearer token
 * @param {String} [groupID] - ID of a specific group to retrieve info from
 */
const getUserAndGroup = async (token, groupID = "") => {
  try {
    const res = await fetch(
      `https://api.sidechat.lol/v1/updates?group_id=${groupID}`,
      {
        method: "GET",
        headers: {
          ...defaultHeaders,
          Authorization: `Bearer ${token}`,
        },
      }
    );
    const json = await res.json();
    return json;
  } catch (err) {
    console.error(err);
    throw new SidechatAPIError(`Failed to get posts from group.`);
  }
};

/**
 * Fetches posts from the specified category in a group
 * @param {String} groupID - group ID
 * @param {String} token - user bearer token
 * @param {"hot"|"recent"|"top"} category - category to filter posts
 * @param {SidechatCursorString} [cursor] - cursor string
 * @returns {{posts: SidechatPostOrComment[], cursor: SidechatCursorString}} List of posts and cursor
 */
const getGroupPosts = async (groupID, token, category = "hot", cursor) => {
  try {
    const res = await fetch(
      `https://api.sidechat.lol/v1/posts?group_id=${groupID}&type=${category}${
        cursor ? "&cursor=" + cursor : ""
      }`,
      {
        method: "GET",
        headers: {
          ...defaultHeaders,
          Authorization: `Bearer ${token}`,
        },
      }
    );
    const json = await res.json();
    return json;
  } catch (err) {
    console.error(err);
    throw new SidechatAPIError(`Failed to get posts from group.`);
  }
};

/**
 * Upvote or downvote, or unvote a post
 * @param {String} postID - post ID to vote on
 * @param {String} token - user bearer token
 * @param {SidechatVoteString} action - whether to upvote, downvote, or reset vote
 */
const setVote = async (postID, token, action) => {
  try {
    const res = await fetch(`https://api.sidechat.lol/v1/posts/set_vote`, {
      method: "POST",
      headers: {
        ...defaultHeaders,
        Authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({
        post_id: postID,
        vote_status: action,
      }),
    });
    const json = await res.json();
    return json;
  } catch (err) {
    console.error(err);
    throw new SidechatAPIError(`Failed to change the vote on post.`);
  }
};

/**
 * Get all the commments on a post
 * @param {String} postID - post ID to get comments for
 * @param {String} token - user bearer token
 * @returns {SidechatPostOrComment[]} list of comments
 */
const getPostComments = async (postID, token) => {
  try {
    const res = await fetch(
      `https://api.sidechat.lol/v1/posts/comments/?post_id=${postID}`,
      {
        method: "GET",
        headers: {
          ...defaultHeaders,
          Authorization: `Bearer ${token}`,
        },
      }
    );
    const json = await res.json();
    // Function to preprocess the comments and organize them into a nested structure
    function preprocessComments(apiComments) {
      // Map to store comments by their IDs for efficient lookup
      const commentMap = new Map();
      // List to store top-level comments
      const topLevelComments = [];

      // Iterate through the API comments
      apiComments.forEach((comment) => {
        // Store the comment in the map with its ID as the key
        commentMap.set(comment.id, comment);
        // Get the parent comment using the reply_post_id
        const parentComment = commentMap.get(comment.reply_post_id);
        // Check if the comment is a top-level comment
        if (
          !parentComment ||
          comment.reply_post_id === comment.parent_post_id
        ) {
          // If it's a top-level comment, push it to the topLevelComments array
          topLevelComments.push(comment);
        } else {
          // If it's a reply, add it to the parent comment's replies array
          if (!parentComment.replies) parentComment.replies = [];
          parentComment.replies.push(comment);
        }
      });

      // Flatten the nested structure and return a single list of comments
      return flattenComments(topLevelComments);
    }

    // Function to flatten nested comments into a single list
    function flattenComments(comments) {
      // Use reduce to flatten the nested comments array into a single list
      return comments.reduce((flatComments, comment) => {
        // Push the current comment to the flatComments array
        flatComments.push(comment);
        // If the current comment has replies, recursively flatten them and push to the flatComments array
        if (comment.replies)
          flatComments.push(...flattenComments(comment.replies));
        // Return the flatComments array
        return flatComments;
      }, []);
    }

    const sortedComments = preprocessComments(json.posts);
    return sortedComments;
  } catch (err) {
    console.error(err);
    throw new SidechatAPIError(`Failed to get comments on post.`);
  }
};

/**
 * Gets groups to be displayed on the "Explore Groups" page
 * @param {String} token - user bearer token
 * @returns {SidechatGroup}
 */
const getAvailableGroups = async (token) => {
  try {
    const res = await fetch(`https://api.sidechat.lol/v1/groups/explore`, {
      method: "GET",
      headers: {
        ...defaultHeaders,
        Authorization: `Bearer ${token}`,
      },
    });
    const json = await res.json();
    return json.groups;
  } catch (err) {
    console.error(err);
    throw new SidechatAPIError(`Failed to get groups from explore.`);
  }
};

export {
  loginViaSMS,
  verifySMSCode,
  setAge,
  setDeviceID,
  registerEmail,
  checkEmailVerification,
  getUserAndGroup,
  getGroupPosts,
  setVote,
  getPostComments,
  getAvailableGroups,
};
